### PR TITLE
new Json approval matcher

### PR DESCRIPTION
**Pull request by gybandi**
New matcher to ease creating expected DTOs.
The matcher takes no argument, it generates the "not approved" expected DTO, which must be verified and renamed by the developer. Subsequent runs will find the "approved" file and assert the actual object to its contents.
Useful for testing REST endpoints, where the response structure could be very complex 

Also extended the GsonProvider with an overloaded gson(...) method with a custom GsonConfiguration object, which can be used to define custom TypeAdapters and TypeHierarchyAdapters.

Special thanks goes to Gabor Karsai for the idea.

_Included JsonMatcherSampleTest.java:_

```
package com.shazam.shazamcrest;

import java.util.Date;

import org.junit.Test;

import com.shazam.shazamcrest.matcher.Matchers;

/**
 * Sample test for using {@link com.shazam.shazamcrest.matcher.Matchers#sameJsonAsApproved()}.
 * @author Andras_Gyuro
 *
 */
public class JsonMatcherSampleTest {

    /**
     * An example for using the Matchers.sameJsonAsApproved() to verify an object.
     * When first run, the test will create the json file that must be checked and renamed by the developer.
     * The generated file name will be placed next to the test files in a directory. The generation algorithm
     * creates SHA-1 hashes from the name of the class and name of the test method and uses these to create the directory name and json
     * file name.
     *
     * The following example will create 'abe6b8\fc5014-not-approved.json' which must be renamed
     * to 'abe6b8\fc5014-approved.json' after it's contents has been verified.
     * The next test run will find this approved file and will assert it's contents to the actual beanChild
     * object.
     */
    @Test
    public void testWithSameJsonAsApprovedMatcher(){
            DummyBean beanParent = new DummyBean(1, "a parent bean", true, null);
            DummyBean beanChild = new DummyBean(2, "a child bean", false, beanParent);

            MatcherAssert.assertThat(beanChild, Matchers.sameJsonAsApproved());
    }


    private class DummyBean{

        private int beanInt;
        private String beanString;
        private Date beanDate;
        private boolean beanBoolean;
        private DummyBean beanParent;

        public DummyBean(int beanInt, String beanString, boolean beanBoolean, DummyBean beanParent) {
            super();
            this.beanInt = beanInt;
            this.beanString = beanString;
            this.beanBoolean = beanBoolean;
            this.beanParent = beanParent;
        }

        public int getBeanInt() {
            return beanInt;
        }

        public String getBeanString() {
            return beanString;
        }

        public boolean isBeanBoolean() {
            return beanBoolean;
        }

    }

}

```

The generated 'abe6b8\fc5014-not-approved.json':

```
/*com.shazam.shazamcrest.JsonMatcherSampleTest.testWithSameJsonAsApprovedMatcher*/
{
  "beanInt": 2,
  "beanString": "a child bean",
  "beanBoolean": false,
  "beanParent": {
    "beanInt": 1,
    "beanString": "a parent bean",
    "beanBoolean": true
  }
}

```

### CODE REVIEW

**Comment by sjuhos** [comment]
It looks useful! :+1:

**Comment by krzysiekbr** [comment]
Hi,
it's been almost a year since this PR was opened. Is there any chance to reactivate and merge it?

**Comment by gybandi** [comment]
@krzysiekbr 
Hi!
I'm not sure if this is going to be merged, but you can use this fork if you need this:
[](https://github.com/karsaig/approvalcrest)

**Comment by krzysiekbr** [comment]
Hi @gybandi 
Thanks for the update. I can't find approvalcrest in maven repository, is it available there?

**Comment by lucanaldini** [comment]
This functionality looks very useful but does not seem to fit the purposes this library was created for in the first place. Ideally I would like to keep its API as light and as focused as possible. @gybandi 's fork should be used instead.

**Pull request closed without merging**
